sudo: required
services:
  - docker

before_install:
  - docker build -t newuserua/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true newuserua/docker-react npm run test -- --coverage
